### ISSUE TITLE
Deep assigning objects with different property types

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/deep-assign#15] opened 2016-01-30 10:35 UTC
I have to assign an object to another that could have prop of different kind.

In this example:

``` js
var assign = require('deep-assign');
assign({ prop: 'test1' }, { prop: ['u'] });
```

deep-assign try to set string characters to elements of the `['u']` array, and it throws
`TypeError: Cannot assign to read only property '0' of [object String]`.
You can test it on [tonicdev](https://tonicdev.com/56ac848c788a1f0d00425fa0/56ac9022879afb0c002c2505)

I was instead expecting to obtain as result   { prop: ['u'] }. That is, I was expecting the whole target `prop` to be overwritten by the source `prop`, being it a string and not an object.

Is this by design? If not , I could write a PR to implement the expectation I explain.

**Comment by schnittstabil** [comment] 2016-01-30 16:13
@parro-it In my opinion that is the expected behavior, because we _recursively Object.assign()_:

``` js
assign({ prop: 'test1' }, { prop: ['u'] });

// should be similar to
{prop: deep_assign('test1', ['u'])}

// which have to be the same as 
{prop: Object.assign('test1', ['u'])}
//=> TypeError: Cannot assign to read only property '0' of [object String]
```

I'm open for suggestions, but please read https://github.com/sindresorhus/deep-assign/issues/13#issuecomment-171201799 first. 

I close this issue, in favor of #13, please reopen if needed.

**Closed as completed by schnittstabil** 2016-01-30 16:13 UTC
